### ISSUE TITLE
feat(bindings-perp): Include an admin set and a function to claim the funds.

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/cw-nibiru#31]
## Context

https://github.com/NibiruChain/nibiru/issues/1378#issuecomment-1554575468

## Tasks

- [x] Implement the admin set
- [x] Implement a function to claim from the contract
- [x] test the admin set
- [x] test the claim function
- [ ] Enforce functions as sudoer-only: `OpenPosition`, `ClosePosition`, etc.
- [ ] Enforce functions as admin-only: `Claim`, `EditSudoers`
- [ ] docs(bindings-perp): Document this contract and its purpose in Markdown.
