### ISSUE TITLE
epic: linear vesting smart contract for investors, advisors, and other contributors

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/cw-nibiru#47]
## Summary

The token agreements defined in the
[tokenomics](https://nibiru.fi/docs/learn/tokenomics.html) will be implemented
via a CosmWasm smart contract. The feature demands (1) a secure and
configurable way to vest tokens linearly over time and (2) an interface for
claiming vested tokens.  

## Sprint 1 - Initial Draft

- [ ] 2023-07-16: Add MVP to the `cw-nibiru` repo. | @jgimeno 
- [ ] Peer audit on initial version | @Unique-Divine 
- [ ] Full test coverage of core business logic 
- [ ] feat: vesting from cliffs with different start times.

## Sprint 2 - Rehearsal

- [ ] Practice setting up the contracts with an SDK group, CW group, or multisig.
- [ ] Automate the setup on a fresh local chain so that it can run as a CI test. 
- [ ] (Maybe) Code4rena or Confio audit?

**Comment by Unique-Divine** [comment]
This is complete. We use this in production already. See core contracts here: https://github.com/NibiruChain/nibiru-wasm/tree/main/contracts#core-contracts
