### ISSUE TITLE
epic(token-vesting): mini audit on token vesting contract

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/cw-nibiru#52]
token vesting contract audit.

- [ ] test(token-vesting): build send msg fn
- [ ] test(token-vesting): register_vesting_account execute handler
- [ ] test(token-vesting): deregister_vesting_account execute handler 
- [ ] test(token-vesting): claim execute handler
- [ ] test(token-vesting): vesting_account query handler
- [ ] feat(token-vesting): It should be possibel to start vests from both the instantiate and execute entry points
- [ ] refactor(token-vesting): (practices) Prefer `expect` over `unwrap` outside of tests.

**Comment by Unique-Divine** [comment]
Complete and running in production: https://github.com/NibiruChain/nibiru-wasm/tree/main/contracts#core-contracts
