### ISSUE TITLE
feat: epic: Add convenient functions for building `StargateMsg` transactions and queries 

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/cw-nibiru#68]
### Tx msgs

- [x] tokenfactory tx msgs
- [x] perp tx msgs
- [x] spot tx msgs
- [x] tokenfactory queries

### Queries 
- [x] perp queries
- [x] spot queries
- [x] oracle queries
- [x] epochs queries

## Rust types are available here:

https://github.com/NibiruChain/cw-nibiru/blob/8d93e73cd3c9f298402cc2118586ea1fc7bcc98c/nibiru-std/src/proto/mod.rs#L107-L135

**Comment by Unique-Divine** [comment]
- Closed by https://github.com/NibiruChain/cw-nibiru/tree/cc1fa0df3a04138169b9fa37e06e57c8373f9700
