### ISSUE TITLE
epic(nusd): Production NUSD smart contracts with multi-collateral support

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/cw-nibiru#90]
More context: [(Notion) NUSD Collateral](https://nibiru.notion.site/NUSD-Collateral-6ba2b59fa2bd45d2badc3037f75e5d56)

### Single-collateral
- [ ] test(nusd/valuator): Migration entry point for state migrations
- [ ] test(nusd/api): Test mint and redeem with test-tube 
- [ ] test(nusd): e2e test NUSD using test-tube or a local network scenario.
- [ ] epic(cw-nibiru): Nibiru-specific test-tube lib with tokenfactory support.

### Multi-collateral: Design
- [ ] epic(nusd/design): Complete design of NUSD with multi-collateral support for initial audit. 
  - [ ] design: Propose variation internally based on stableswap logic
  - [ ] design: Propose variation based on oracles

### Multi-collateral: Impl

- [ ] epic(nusd): Create multi-collateral implementation with unit tests
- [ ] test(nusd): e2e test NUSD using test-tube or a local network scenario.
